import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/context/ThemeContext';
import { AuthProvider } from '@/context/AuthContext';
import Layout from '@/components/layout/Layout';
import dynamic from "next/dynamic";
const ClientProtect = dynamic(() => import("@/components/shared/ClientProtect"), { ssr: false });

// Import global Tailwind CSS styles for the entire app
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The Inter font and global styles are applied to the body */}
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <Layout>
              <ClientProtect>{children}</ClientProtect>
            </Layout>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
