import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// Import global Tailwind CSS styles for the entire app
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The Inter font and global styles are applied to the body */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
