name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Run lint
      - run: npm run lint

      # Run type-check
      - run: npm run type-check

      # Run tests
      - run: npm run test

      # Build Next.js app
      - run: npm run build
